---
abstract: 'Encapsulate a common Catalyst Pattern for getting a path'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Component::InstancePerContext: '0'
  Catalyst::Test: '0'
  File::Spec: '0'
  FindBin: '0'
  HTTP::Request::Common: '0'
  Test::Most: '0.34'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-ComponentRole-PathFrom
requires:
  Catalyst::Component::ApplicationAttribute: '0'
  File::Spec: '0'
  Moose: '2.1403'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-ComponentRole-PathFrom/issues
  homepage: https://github.com/jjn1056/Catalyst-ComponentRole-PathFrom
  repository: https://github.com/jjn1056/Catalyst-ComponentRole-PathFrom.git
version: '0.002'
